### ISSUE TITLE
RFC: getting source file path for findClosestMapping

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/source-map#15]
There is currently no way to get the sourcfile with `findClosestMapping` (only the index).

https://github.com/parcel-bundler/source-map/blob/a09800c0b44703883a2814dee396a39c75ed43dc/src/node.js#L110-L112

Two options:
- Return `IndexedMapping<string>` because this function isn't used in performance-critical code (right?)
- add `getSource(index: number): string` as a counterpart for `getSourceIndex(source: string): number` (and same for name).
- or both?

**Comment by DeMoorJasper** [comment]
@mischnic awesome idea, was gonna improve source, name handling slightly anyway so this is a great addition to this :)

Not entirely sure how we should do the index vs string thing on indexedmappings without complicating the types too much. I'll probably end up just always return string values instead of indexes, as you're saying it's never used in performance critical places.

I'll implement this in a couple hours, a PR should be ready by tonight.
