### ISSUE TITLE
Is `delete()` necessary to avoid memory leaks, if I allow a SourceMap instance to be GCed by JS?

### ISSUE THREAD

**Issue by cspotcode** [parcel-bundler/source-map#97]
The README says that `delete()` will remove references in native code.  But if I *don't* call `delete()`, and allow my `SourceMap`s to be garbage collected by JS, will that cause a memory leak?

```
// Does this pseudo-code cause a memory leak since it does not call delete()?
while(true) {
  const sm = new SourceMap();
  sm.addVLQMap(dataFromSomewhere); // etc
  // is GCed because we drop the JS reference
}
```

**Comment by devongovett** [comment]
With the WASM version, yes, delete is necessary. With the node version it is not.

**Comment by mischnic** [comment]
Huh, they are missing from 2.0.1 and newer...

https://unpkg.com/browse/@parcel/source-map@2.0.0/parcel_sourcemap_wasm/
https://unpkg.com/browse/@parcel/source-map@2.0.1/parcel_sourcemap_wasm/
https://unpkg.com/browse/@parcel/source-map@2.0.2/parcel_sourcemap_wasm/

**Comment by mischnic** [comment]
Are you trying to use the Wasm version from Node or in the browser? Looks like we only build the browser version anyway (which works fine with version 2.0.0 and a bundler that uses the `browser` field in package.json)

To give more background to the delete question: the `SourceMap` wrapped object will be GCed, but not associated memory in the Wasm memory block. At some point in the future, we could use `FinalizationRegistry` to run `delete` automatically.

Another thing you need to do in the wasm version is await the `init` export 
https://github.com/parcel-bundler/source-map/blob/c4b0b249ac623152073e188ea92d212589661610/src/wasm.js#L8
so that all other operations don't have to wait for the Wasm instance to be loaded and can be synchronous (= what top-level-await was built to solve).

**Comment by cspotcode** [comment]
Ok thanks.  Yeah I was trying to use the wasm version from node.  For my use-case, it's important that I automatically and silently fallback to a non-native binary in case the native binary fails in a target environment, so I was testing if that would work.  I think the async bootstrapping might also be a deal-breaker, due to legacy constraints in my project, though I do understand why WASM often necessitates it in browsers.

I appreciate your taking the time to share this information, thank you.

**Comment by mischnic** [comment]
The Wasm-in-Node usecase wasn't needed by anyone so far. But in Node, this could be implement without require as well (readFileSync + `new WebAssembly.Module(buffer)`).
